[package]
name = "primitives"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
heapsize = "0.4"
rustc-hex = "2"
byteorder = "1.0"
bigint = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
