[workspace]
members = [ "chain",
            "crypto",
            "keys",
            "primitives",
            "script",
            "serialization",
            "serialization_derive",
            "wallet",
            ]




